# Turbo Engine data description

CMAPSS stands for Commercial Modular Aero-Propulsion System Simulation. It is a system developed by NASA to study engine degradation. It is coded in MATLAB and Simulink (A toolbox of MATLAB). 

The engine under study is a turbofan engine (a jet engine). A turbofan engine has many components. A few important components are: Fan, Low Pressure Compressor (LPC), High Pressure Compressor (HPC), Low Pressure Turbine (LPT), High Pressure Turbine (HPT). 

During operation, degradation occurs in each of the components. If degradation level in any component exceeds a threshold, the engine is said to have failed. We don't want jet engines to fail mid-air. Therefore, jet engines are inspected before every take off. This is a form of periodic maintenance that is not cost effective. 

But given the critical nature of operation (considering human lives involved), this form of maintenance strategy is justified. Even then, we need a system that can given us early warning if something is going to fail. 

An early warning, in many cases, may help us prepare for the problem, if not prevent it altogether. A sufficiently early warning will enable us to prevent the disaster. But if an early warning is too conservative, it will lead to unnecessary waste of money. So, aim of a predictive maintenance system is to predict the RUL as accurately as possible such that it is neither too early nor too late.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [8]:
df = pd.read_csv('train_FD001.txt', sep=' ', header = None)

data=pandas.read_csv(‘filename.txt’, sep=’ ‘, header=None, names=[“Column1”, “Column2”])

Parameters:

- filename.txt: As the name suggests it is the name of the text file from which we want to read data.
- sep: It is a separator field. In the text file, we use the space character(‘ ‘) as the separator.
- header: This is an optional field. By default, it will take the first line of the text file as a header. If we use header=None then it will create the header.
- names: We can assign column names while importing the text file by using the names argument.

In [9]:
df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,NaN,NaN
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735,NaN,NaN
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594,NaN,NaN
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333,NaN,NaN
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640,NaN,NaN
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522,NaN,NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20631 non-null  int64
 1   1       20631 non-null  int64
 2   2       20631 non-null  float64
 3   3       20631 non-null  float64
 4   4       20631 non-null  float64
 5   5       20631 non-null  float64
 6   6       20631 non-null  float64
 7   7       20631 non-null  float64
 8   8       20631 non-null  float64
 9   9       20631 non-null  float64
 10  10      20631 non-null  float64
 11  11      20631 non-null  float64
 12  12      20631 non-null  float64
 13  13      20631 non-null  float64
 14  14      20631 non-null  float64
 15  15      20631 non-null  float64
 16  16      20631 non-null  float64
 17  17      20631 non-null  float64
 18  18      20631 non-null  float64
 19  19      20631 non-null  float64
 20  20      20631 non-null  float64
 21  21      20631 non-null  int64
 22  22      20631 non-null  int64
 23  23      20631 non-null  float64
 24  24      20631 non-null  float64
 25  25      20631 non-null  float64
 26  26      0 non-null      float64
 27  27      0 non-null      float64
dtypes: float64(24), int64(4)
memory usage: 4.4 MB

In [12]:
df = df.drop([26,27], axis=1)

In [16]:
df

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [17]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20631 non-null  int64
 1   1       20631 non-null  int64
 2   2       20631 non-null  float64
 3   3       20631 non-null  float64
 4   4       20631 non-null  float64
 5   5       20631 non-null  float64
 6   6       20631 non-null  float64
 7   7       20631 non-null  float64
 8   8       20631 non-null  float64
 9   9       20631 non-null  float64
 10  10      20631 non-null  float64
 11  11      20631 non-null  float64
 12  12      20631 non-null  float64
 13  13      20631 non-null  float64
 14  14      20631 non-null  float64
 15  15      20631 non-null  float64
 16  16      20631 non-null  float64
 17  17      20631 non-null  float64
 18  18      20631 non-null  float64
 19  19      20631 non-null  float64
 20  20      20631 non-null  float64
 21  21      20631 non-null  int64
 22  22      20631 non-null  int64
 23  23      20631 non-null  float64
 24  24      20631 non-null  float64
 25  25      20631 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 4.1 MB

All independent features are numeric and no null values in any independent features. Thats Great!!

In [30]:
# Assign names to independent features

index_names = ['engine_number', 'time (in cycles)']
setting_names = ['Operational_setting_1', 'Operational_setting_2', 'Operational_setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio) ",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
column_names = index_names + setting_names + sensor_names

In [31]:
df.columns = column_names

In [32]:
df.head()

,engine_number,time (in cycles),Operational_setting_1,Operational_setting_2,Operational_setting_3,(Fan inlet temperature) (◦R),(LPC outlet temperature) (◦R),(HPC outlet temperature) (◦R),(LPT outlet temperature) (◦R),(Fan inlet Pressure) (psia),...,(Ratio of fuel flow to Ps30) (pps/psia),(Corrected fan speed) (rpm),(Corrected core speed) (rpm),(Bypass Ratio),(Burner fuel-air ratio),(Bleed Enthalpy),(Required fan speed),(Required fan conversion speed),(High-pressure turbines Cool air flow),(Low-pressure turbines Cool air flow)
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [40]:
for col in df.columns:
    print(df[col].value_counts())
    print("*"*20)

engine_number
69    362
92    341
96    336
67    313
83    293
     ...
24    147
57    137
70    137
91    135
39    128
Name: count, Length: 100, dtype: int64
********************
time (in cycles)
1      100
66     100
97     100
96     100
95     100
      ...
346      1
345      1
343      1
342      1
362      1
Name: count, Length: 362, dtype: int64
********************
Operational_setting_1
 0.0000    413
 0.0002    398
 0.0004    394
-0.0005    390
 0.0001    382
          ...
-0.0075      1
 0.0087      1
-0.0087      1
-0.0078      1
 0.0077      1
Name: count, Length: 158, dtype: int64
********************
Operational_setting_2
-0.0003    2104
 0.0001    2097
 0.0000    2070
 0.0003    2065
-0.0004    2051
-0.0002    2049
 0.0002    2038
-0.0001    2029
 0.0004    1997
 0.0005    1068
-0.0005     958
 0.0006      71
-0.0006      34
Name: count, dtype: int64
********************
Operational_setting_3
100.0    20631
Name: count, dtype: int64
********************
(Fan inlet temperature) (◦R)
518.67    20631
Name: count, dtype: int64
********************
(LPC outlet temperature) (◦R)
642.50    190
642.56    189
642.53    188
642.60    184
642.67    179
         ...
641.31      1
644.47      1
644.35      1
644.50      1
644.39      1
Name: count, Length: 310, dtype: int64
********************
(HPC outlet temperature) (◦R)
1590.10    27
1589.76    26
1589.98    25
1592.11    25
1587.86    24
           ..
1605.75     1
1608.80     1
1605.90     1
1609.02     1
1610.87     1
Name: count, Length: 3012, dtype: int64
********************
(LPT outlet temperature) (◦R)
1409.01    20
1404.47    18
1407.15    18
1407.02    18
1414.03    18
           ..
1427.32     1
1432.90     1
1436.58     1
1405.11     1
1432.14     1
Name: count, Length: 4051, dtype: int64
********************
(Fan inlet Pressure) (psia)
14.62    20631
Name: count, dtype: int64
********************
(bypass-duct pressure) (psia)
21.61    20225
21.60      406
Name: count, dtype: int64
********************
(HPC outlet pressure) (psia)
553.62    116
553.76    115
553.72    110
553.94    110
553.43    108
         ...
550.72      1
555.60      1
555.72      1
555.86      1
550.79      1
Name: count, Length: 513, dtype: int64
********************
(Physical fan speed) (rpm)
2388.11    1181
2388.10    1159
2388.09    1149
2388.08    1126
2388.07    1077
2388.12    1069
2388.06    1050
2388.13    1033
2388.05    1013
2388.04     910
2388.14     881
2388.03     879
2388.02     812
2388.15     809
2388.01     754
2388.16     680
2388.17     567
2388.00     544
2388.18     479
2387.99     426
2388.19     393
2387.98     339
2388.20     318
2388.21     253
2388.22     227
2388.23     210
2387.97     201
2388.24     147
2387.96     145
2388.25     137
2388.26     121
2388.27      92
2388.28      87
2388.29      72
2387.95      72
2388.30      50
2388.31      37
2388.32      34
2387.94      33
2387.93      16
2388.33      13
2388.34      13
2387.92       9
2387.91       3
2388.35       2
2388.44       2
2388.50       1
2388.36       1
2388.37       1
2387.90       1
2388.52       1
2388.46       1
2388.56       1
Name: count, dtype: int64
********************
(Physical core speed) (rpm)
9058.88    16
9060.37    15
9060.55    15
9056.86    15
9063.22    15
           ..
9132.15     1
9133.05     1
9139.16     1
9134.14     1
9071.43     1
Name: count, Length: 6403, dtype: int64
********************
(Engine pressure ratio(P50/P2)
1.3    20631
Name: count, dtype: int64
********************
(HPC outlet Static pressure) (psia)
47.46    341
47.57    338
47.49    332
47.45    332
47.47    331
        ...
46.90      1
46.91      1
48.43      1
46.85      1
48.48      1
Name: count, Length: 159, dtype: int64
********************
(Ratio of fuel flow to Ps30) (pps/psia)
521.63    143
521.42    136
521.35    131
521.56    129
521.66    126
         ...
523.09      1
523.11      1
523.31      1
519.02      1
519.18      1
Name: count, Length: 427, dtype: int64
********************
(Corrected fan speed) (rpm)
2388.10    1164
2388.09    1144
2388.08    1129
2388.11    1127
2388.07    1112
2388.12    1099
2388.06    1005
2388.05     987
2388.13     976
2388.04     952
2388.14     914
2388.03     855
2388.15     817
2388.02     790
2388.01     699
2388.16     665
2388.00     573
2388.17     558
2388.18     443
2387.99     440
2388.19     387
2387.98     352
2388.20     330
2388.21     258
2388.22     231
2388.23     221
2387.97     219
2387.96     170
2388.24     160
2388.25     137
2388.26     121
2388.27     102
2387.95      95
2388.28      89
2388.29      61
2387.94      54
2388.30      44
2388.31      33
2388.32      29
2388.33      22
2387.93      19
2387.92      12
2388.34       8
2388.35       7
2388.36       6
2388.37       3
2388.39       2
2387.91       2
2387.89       1
2387.88       1
2388.44       1
2388.56       1
2388.55       1
2388.49       1
2388.54       1
2387.90       1
Name: count, dtype: int64
********************
(Corrected core speed) (rpm)
8138.89    17
8141.85    17
8136.89    16
8140.79    15
8140.65    15
           ..
8116.11     1
8120.74     1
8117.92     1
8122.77     1
8149.90     1
Name: count, Length: 6078, dtype: int64
********************
(Bypass Ratio)
8.4309    38
8.4318    37
8.4468    36
8.4442    35
8.4128    34
          ..
8.5465     1
8.5334     1
8.5406     1
8.5559     1
8.5389     1
Name: count, Length: 1918, dtype: int64
********************
(Burner fuel-air ratio)
0.03    20631
Name: count, dtype: int64
********************
(Bleed Enthalpy)
393    5445
392    4578
394    4063
395    2339
391    2022
396    1185
390     452
397     436
398      72
389      30
399       7
388       1
400       1
Name: count, dtype: int64
********************
(Required fan speed)
2388    20631
Name: count, dtype: int64
********************
(Required fan conversion speed)
100.0    20631
Name: count, dtype: int64
********************
(High-pressure turbines Cool air flow)
38.86    485
38.89    476
38.82    472
38.87    460
38.85    458
        ...
39.28      1
39.34      1
39.32      1
39.43      1
38.14      1
Name: count, Length: 120, dtype: int64
********************
(Low-pressure turbines Cool air flow)
23.3222    23
23.3029    17
23.2896    16
23.3725    16
23.3710    15
           ..
23.4609     1
23.5294     1
23.5176     1
23.4764     1
22.9333     1
Name: count, Length: 4745, dtype: int64
********************

In [58]:
df[df['engine_number'] == 1]

,engine_number,time (in cycles),Operational_setting_1,Operational_setting_2,Operational_setting_3,(Fan inlet temperature) (◦R),(LPC outlet temperature) (◦R),(HPC outlet temperature) (◦R),(LPT outlet temperature) (◦R),(Fan inlet Pressure) (psia),...,(Ratio of fuel flow to Ps30) (pps/psia),(Corrected fan speed) (rpm),(Corrected core speed) (rpm),(Bypass Ratio),(Burner fuel-air ratio),(Bleed Enthalpy),(Required fan speed),(Required fan conversion speed),(High-pressure turbines Cool air flow),(Low-pressure turbines Cool air flow)
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,1,188,-0.0067,0.0003,100.0,518.67,643.75,1602.38,1422.78,14.62,...,519.79,2388.23,8117.69,8.5207,0.03,396,2388,100.0,38.51,22.9588
188,1,189,-0.0006,0.0002,100.0,518.67,644.18,1596.17,1428.01,14.62,...,519.58,2388.33,8117.51,8.5183,0.03,395,2388,100.0,38.48,23.1127
189,1,190,-0.0027,0.0001,100.0,518.67,643.64,1599.22,1425.95,14.62,...,520.04,2388.35,8112.58,8.5223,0.03,398,2388,100.0,38.49,23.0675
190,1,191,-0.0000,-0.0004,100.0,518.67,643.34,1602.36,1425.77,14.62,...,519.57,2388.30,8114.61,8.5174,0.03,394,2388,100.0,38.45,23.1295
191,1,192,0.0009,-0.0000,100.0,518.67,643.54,1601.41,1427.20,14.62,...,520.08,2388.32,8110.93,8.5113,0.03,396,2388,100.0,38.48,22.9649

In [55]:
df[df['engine_number'] == 1]['time (in cycles)'].values[-1]

0        1
1        2
2        3
3        4
4        5
      ...
187    188
188    189
189    190
190    191
191    192
Name: time (in cycles), Length: 192, dtype: int64

In [59]:
EOL = []

for engine_number in df['engine_number']:
    EOL.append(df[df['engine_number'] == engine_number]['time (in cycles)'].values[-1])

In [60]:
EOL

[192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 179,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 189,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 269,
 ...]